### ISSUE TITLE
Issues on RTX 3070: cuda_set_device()

### ISSUE THREAD

**Issue by lnx00** [maalik0786/FastYolo#18]
I've been trying to get FastYolo to work for the past hour, but I'm stuck at this issue:
```
CUDA allocate done!
CUDA status Error: file: C:\Code\Github\darknet\src\dark_cuda.c : cuda_set_device() : line: 38 : build time: Mar 15 2022 - 19:37:49

 CUDA Error: driver shutting down
```

I'm using an RTX 3070 FE on Windows 10. CUDA 11.6 and CUDNN 8.3.2 are correctly installed _(I did also try other CUDA/CUDNN versions)_ as described in the README and i've also included the NuGet package in my project (.NET 6). I have also made sure that I'm using the latest NVIDIA drivers.

The issue occurs after initializing the YoloWrapper instance like this:
```cs
YoloWrapper yoloWrapper = new(configPath, weigthsPath, namesPath);
```
I did try my own training data, as well as the example provided on this repo but i always come to the same result.

Does anyone know what could be causing this issue? I'm really frustrated and would like to fix this

[Console Log](https://pastebin.com/raw/F01X1y0a)

**Comment by celadaris** [comment]
i have a similar issue, im using the rtx 3080 laptop version
i posted my thread [here](https://github.com/maalik0786/FastYolo/issues/23#issue-1525255038)

**Comment by celadaris** [comment]
i was able to fix the error for myself, check out the thread and see if it helps you too.
